name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - '*'
    - '!feedback'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  # job to run autograding
  grade:
    name: Autograding
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
