name: GitHub Classroom Workflow

on:
  issue_comment:                                     
    types: [created, edited, deleted]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  # job to run autograding
  grade:
    name: Autograding
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'run grading') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: education/autograding@v1
