# reusable workflow that parses files from artifact directory, renders them
# through a template, and publishes render to PR or step summary.

name: Feedback Reusable Workflow
on:
  workflow_call:
    inputs:
      pr-template:
        description: 'Template to use for PR comments'
        required: false
        type: string
      pr-title:
        description: 'Title of the PR to post feedback to'
        default: 'Feedback'
        required: false
        type: string
      pr-base:
        description: 'Base branch of the PR to post feedback to'
        default: 'feedback'
        required: false
        type: string
      pr-branch:
        description: 'Branch of the PR to post feedback to'
        default: ${{ github.event.repository.default_branch }}
        required: false
        type: string
    secrets:
      token:
        description: 'Token to use for PR comments'
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  feedback:
    name: Feedback
    runs-on: ubuntu-latest
    steps:
      # checkout repo to access template files
      - name: Checkout
        uses: actions/checkout@v4

      - if: ${{ !inputs.pr-template }}
        run: echo "no PR template proved, skipping PR feedback"

      # find PR if it exists
      - name: Find PR number
        if: ${{ inputs.pr-template }}
        uses: markpatterson27/find-pull-request-action@pre-pr-release-v1.8.0  # TODO: update to latest version
        id: find-pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          title: ${{ inputs.pr-title }}
          base: ${{ inputs.pr-base }}
          branch: ${{ inputs.pr-branch }} # TODO: get default branch name from env content
          state: all
